# Generated by Django 2.0.5 on 2018-06-25 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('apellidos', models.CharField(blank=True, max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=100)),
                ('cv', models.FileField(upload_to='static/cvs')),
            ],
        ),
        migrations.CreateModel(
            name='Vacantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('zona', models.CharField(max_length=100)),
                ('requisitos', models.CharField(max_length=100)),
                ('oferta', models.CharField(max_length=100)),
                ('mensaje', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='candidato',
            name='vacante',
            field=models.ManyToManyField(to='website.Vacantes'),
        ),
    ]
