# Generated by Django 2.0.5 on 2018-06-03 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=None, max_length=100)),
                ('last_name', models.CharField(blank=None, max_length=100)),
                ('phone', models.CharField(blank=None, max_length=10)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
