# Generated by Django 2.0.5 on 2018-06-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_custommer_poject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('project_leader', models.CharField(max_length=100)),
                ('progress', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Poject',
        ),
    ]
