# Generated by Django 2.0.5 on 2018-06-19 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0004_auto_20180610_1403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='progress',
            new_name='project_address',
        ),
        migrations.AddField(
            model_name='project',
            name='project_city',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_custommer',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_end_date',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_estimate_meters',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_machine',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_machine_operator',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_observations',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='project_price_per_meter',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_real_meters',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_seller',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_start_date',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='custommer',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proyectos.Person'),
        ),
    ]
