# Generated by Django 2.0.5 on 2018-06-19 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0005_auto_20180619_0342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logbooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.CharField(default='yyyy/mm/dd', max_length=100)),
                ('log_task', models.CharField(default='NULL', max_length=100)),
                ('log_meters', models.CharField(default='0', max_length=100)),
                ('log_total_meters', models.CharField(default='0', max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proyectos.Project')),
            ],
        ),
    ]
