# Generated by Django 2.0.5 on 2018-06-22 02:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0006_logbooks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_end_date',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_real_meters',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_start_date',
            field=models.DateTimeField(default=datetime.datetime.now, max_length=100),
        ),
    ]
