# Generated by Django 2.0.5 on 2018-06-23 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0009_auto_20180623_0147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_project',
            new_name='project_progress',
        ),
    ]
