# Generated by Django 2.0.5 on 2018-06-24 17:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0011_auto_20180623_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logbooks',
            name='log_date',
            field=models.CharField(default=datetime.date.today, max_length=100),
        ),
    ]
